/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 2b273f89d2a7f7beb3948be3686cd60f)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	SANITY_STUDIO_PROJECT_ID: string;
	SANITY_STUDIO_DATASET: string;
	SANITY_STUDIO_PREVIEW_ORIGIN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SANITY_STUDIO_PROJECT_ID" | "SANITY_STUDIO_DATASET" | "SANITY_STUDIO_PREVIEW_ORIGIN">> {}
}
