import { PackageIcon } from '@sanity/icons/Package'
import { defineArrayMember, defineField, defineType } from 'sanity'

export const productType = defineType({
  name: 'product',
  title: 'Sản phẩm',
  type: 'document',
  icon: PackageIcon,
  groups: [
    { name: 'content', title: 'Nội dung', default: true },
    { name: 'media', title: 'Hình ảnh & tài liệu' },
    { name: 'organization', title: 'Phân loại' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Tên sản phẩm',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required().max(140),
    }),
    defineField({
      name: 'slug',
      title: 'Đường dẫn',
      type: 'slug',
      group: 'content',
      options: { source: 'title', maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({ name: 'model', title: 'Model', type: 'string', group: 'content' }),
    defineField({ name: 'sku', title: 'Mã sản phẩm / SKU', type: 'string', group: 'content' }),
    defineField({
      name: 'shortDescription',
      title: 'Mô tả ngắn',
      type: 'text',
      rows: 4,
      group: 'content',
      validation: (rule) => rule.max(320),
    }),
    defineField({ name: 'description', title: 'Nội dung chi tiết', type: 'blockContent', group: 'content' }),
    defineField({
      name: 'specifications',
      title: 'Thông số kỹ thuật',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({ type: 'specification' })],
    }),
    defineField({
      name: 'mainImage',
      title: 'Ảnh đại diện',
      type: 'imageWithAlt',
      group: 'media',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'gallery',
      title: 'Album ảnh',
      type: 'array',
      group: 'media',
      of: [defineArrayMember({ type: 'imageWithAlt' })],
    }),
    defineField({
      name: 'downloads',
      title: 'Catalogue / Datasheet',
      type: 'array',
      group: 'media',
      of: [defineArrayMember({ type: 'download' })],
    }),
    defineField({
      name: 'brand',
      title: 'Hãng sản xuất',
      type: 'reference',
      group: 'organization',
      to: [{ type: 'brand' }],
    }),
    defineField({
      name: 'categories',
      title: 'Danh mục',
      type: 'array',
      group: 'organization',
      of: [defineArrayMember({ type: 'reference', to: [{ type: 'category' }] })],
      validation: (rule) => rule.min(1).warning('Nên chọn ít nhất một danh mục.'),
    }),
    defineField({
      name: 'tags',
      title: 'Thẻ',
      type: 'array',
      group: 'organization',
      of: [defineArrayMember({ type: 'reference', to: [{ type: 'tag' }] })],
    }),
    defineField({
      name: 'featured',
      title: 'Sản phẩm nổi bật',
      type: 'boolean',
      group: 'organization',
      initialValue: false,
    }),
    defineField({
      name: 'archived',
      title: 'Ngừng hiển thị',
      type: 'boolean',
      group: 'organization',
      initialValue: false,
    }),
    defineField({ name: 'publishedAt', title: 'Ngày xuất bản', type: 'datetime', group: 'organization' }),
    defineField({
      name: 'relatedProducts',
      title: 'Sản phẩm liên quan',
      type: 'array',
      group: 'organization',
      of: [defineArrayMember({ type: 'reference', to: [{ type: 'product' }] })],
    }),
    defineField({ name: 'seo', title: 'SEO', type: 'seo', group: 'seo' }),
  ],
  orderings: [
    { title: 'Mới cập nhật', name: 'updatedDesc', by: [{ field: '_updatedAt', direction: 'desc' }] },
    { title: 'Tên A-Z', name: 'titleAsc', by: [{ field: 'title', direction: 'asc' }] },
  ],
  preview: {
    select: { title: 'title', subtitle: 'model', media: 'mainImage.image' },
  },
})
